name: ðŸ› Roku bug report
description: Report a bug/issue affecting the Hydravion Roku Channel
labels: ["bug"]
body:
    - type: checkboxes
      attributes:
        label: Checklist before submitting a bug report
        options:
        - label: This bug/issue is affecting the Hydravion Roku Channel
          required: true
        - label: I've searched for existing [issues](https://github.com/bmlzootown/Hydravion/issues?q=is:issue) and found no duplicates
          required: true
        - label: I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed
          required: true

    - type: input
      id: devicemodel
      attributes:
          label: Device Model
          description: Settings --> System --> About, Model
          placeholder: e.g. 4660X - Roku Ultra
      validations:
          required: true

    - type: input
      id: osversion
      attributes:
          label: OS Version
          description: Settings --> System --> About, Software version
          placeholder: e.g. 11.5.0 build 4312-46
      validations:
          required: true

    - type: input
      id: channelversion
      attributes:
          label: Channel Version
          description: Highlight channel, access options (*) menu, see "version X.X build X"
          placeholder: e.g. 2.1 build 3
      validations:
          required: true

    - type: input
      id: subscriptions
      attributes:
          label: Whom you are subscribed to?
          description: Sometimes issues are subscription specific
          placeholder: e.g. LTT, Garbage Time, Bitwit, Lvl1
      validations:
          required: true

    - type: markdown
      attributes:
        value: Please detail one bug per GitHub issue

    - type: textarea
      id: details
      attributes:
        label: Error/Issue Details
        description: |
          What is the issue you're experiencing? How can we re-produce it?
          Please be as specific as possible
          - Is the error/issue occurring on a specific channel only?
          - Does it only affect specific videos?
          - Does the issue still occur when trying to play the video at a different resolution? (Access the options menu when looking at the video description, "Select Resolution")
          - Can you provide any screenshots?
        placeholder: Detailed explanation of the issue along with replication steps
